{
 "title": "Airflow",
 "tags": [ "data" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "targets": [
    { "expr": "af_agg_scheduler_heartbeat", "legendFormat": "{{stars}}" }
   ]
  },
  {
   "title": "Dagbag size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "af_agg_dagbag_size" }
   ]
  },
  {
   "title": "DAG processing total parse time",
   "type": "stat",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dag_processing_total_parse_time",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dag_processing_import_errors"
    }
   ]
  },
  {
   "title": "Zombies killed",
   "type": "stat",
   "description": "Zombie tasks killed",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_zombies_killed" }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_ti_successes" }
   ]
  },
  {
   "title": "Operator success rate per minuite",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(af_agg_operator_successes[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Operator failure rate per minute",
   "type": "graph",
   "description": "Total failures of given operator",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(af_agg_operator_failures[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_ti_failures" }
   ]
  },
  { "title": "Executor Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Jobs started per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(af_agg_job_start[1m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Executor open slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_executor_open_slots" }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_executor_queued_tasks" }
   ]
  },
  {
   "title": "Jobs ended per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(af_agg_job_end[1m]) * 60", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_executor_running_tasks" }
   ]
  },
  { "title": "DAG stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Success DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_success * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach failed state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_failed * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "graph",
   "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (dag_id, quantile) (af_agg_dag_task_duration) * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run dependency check time",
   "type": "graph",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_dependency_check * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run schedule delay",
   "type": "graph",
   "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_schedule_delay * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  }
 ]
}